export * from './home';
export {default as RegisterUser} from './register user/component/index';
export {default as Login} from './login/component/index';
export {default as Forgot} from './forgot/component/index';
export {default as ResetPassword} from './reset password/component/index';
export {default as UserInformation} from './user information/component/index';
export {default as User} from './user/component/index';
export {default as ChangePassword} from './change password/component/index';
export {default as RegisterDriver} from './register driver/component/index';
export {default as DriverProduct} from './driver product/component/index';
export {default as DriverProductDetail} from './driver product details/component/index';
export {default as EmailCheck} from './confirm/component/index';
export {default as UserOrder} from './user order/component/index';
export {default as DriverOrderDetail} from './driver order detail/component/index';
export {default as DriverOrderProcessDetail} from './driver order process detail/component/index';
export {default as UserProductDetail} from './user product detail/component/index';
export {default as UserCreateProduct} from './user create product/component/index';
export {default as DriverInfo} from './driver information/component/index';
export * as PaymentComponents from './payment';
export * as ErrorPages from './errors';
export {default as UserProductHistory} from './user product history/component/index';
export {default as UserProductHistoryDetails} from './user product history details/component/index';
export {default as DriverHistory} from './driver order history/component/index';
export {default as AcceptDriver} from './accept driver/component/index';
export {default as AdminInformation} from './admin infomation/component/index';
export {default as DriverActiveOrder} from './driver active order/component';
export {default as UserManagement} from './user management/component/index';
export {default as TotalOrder} from './admin orders/component/index';
export {default as AdminOrderDetail} from './admin order detail/component/index';
export {default as DriverDetail} from './driver detail/component/index';
export {default as PreventDriver} from './prevent driver/component/index';
export {default as AdminInvoices} from './admin invoices/components';
export {default as Verify} from './verify/component';
export {EmailForgot} from './forgot/component/emailForgot';
export {default as Invoice} from './invoice/invoice';
export {default as NonRouting} from './nonRouting/component/index'