export * from './home';
export {default as RegisterUser} from './register user/component/index';
export {default as Login} from './login/component/index';
export {default as Forgot} from './forgot/component/index';
export {default as ResetPassword} from './reset password/component/index';
export {default as UserInformation} from './user information/component/index';
export {default as User} from './user/component/index';
export {default as ChangePassword} from './change password/component/index';
export {default as RegisterDriver} from './register driver/component/index';
export {default as DriverProduct} from './driver product/component/index';
export {default as DriverProductDetail} from './driver product details/component/index';
export {default as EmailCheck} from './confirm/component/index';
export {default as Order} from './order/component/index';
export {default as OrderDetail} from './order detail/component/index';
export {default as OrderProcessDetail} from './order process detail/component/index';
export {default as SenderDashBoard} from './register sender/component/index';
export {default as SenderProduct} from './sender product/component/index';
export {default as SenderProductDetail} from './sender product detail/component/index';
export {default as CreateProduct} from './create product/component/index';
export {default as SenderInfo} from './sender information/component/index';
export {default as DriverInfo} from './driver information/component/index';
export {default as UserProductHistory} from './user product history/component/index';
export {default as UserProductHistoryDetails} from './user product history details/component/index';
export {default as DriverHistory} from './driver order history/component/index';
export {default as AcceptDriver} from './accept driver/component/index';
export {default as AdminInformation} from './admin infomation/component/index';
export {default as UserManagement} from './user management/component/index';
export {default as TotalOrder} from './admin orders/component/index';
export {default as AdminOrderDetail} from './admin order detail/component/index'
export * as PaymentComponents from './payment';